#!/bin/bash


mkdir ~/virtual-machines
cd ~/virtual_machines

wget -c https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.0/FreeBSD-12.0-RELEASE-amd64-disc1.iso

VBoxManage createhd --filename /VirtualBox/FreeBSD/FreeBSD.vdi --size 12000
VBoxManage createvm -name "FreeBSD" -register -memory "1024MB" --ostype FreeBSD_64
VBoxManage storagectl FreeBSD --name "SATA Controller" --add sata \
>  --controller IntelAHCI
$ VBoxManage storageattach FreeBSD --storagectl "SATA Controller" --port 0 \
>  --device 0 --type hdd --medium /VirtualBox/FreeBSD/FreeBSD.vdi

VBoxManage storagectl $VM --name "IDE Controller" --add ide

VBoxManage storageattach $VM --storagectl "IDE Controller" --port 0 \
>  --device 0 --type dvddrive --medium /path/to/windows_server_2008.iso
