#!/bin/bash

Atom_Install=apm install
Atom_Install+=atom-python-run city-lights-ui  Hydrogen linter mathjax-wrapper
Atom_Install+=autocomplete-bash-builtins  counter ide-bash linter-gcc
Atom_Install+=pandoc-convert autocomplete-mathjax dash ide-python linter-ui-default
Atom_Install+=python-tools autocomplete-python data-atom intentions
Atom_Install+=markdown-preview-enhanced busy-signal git-plus language-sql-mysql
Atom_Install+=markdown-preview-plus city-lights-syntax gpp-compiler
Atom_Install+=language-x86-64-assembly markdown-writer
